### PR TITLE
Release

### PR DESCRIPTION
**Pull request by steinwaywhw**
FIx some release scripts for building docker.

### CODE REVIEW

**Comment by githwxi** [comment]
There seems to be some issue with the part of building Docker image.

**Review by githwxi — APPROVED** [review]

**Comment by steinwaywhw** [comment]
I think in the pull-request build, some travis-ci hashed password can't be properly decrypted because it is encrypted with the ats-postiats-release repo.

**Comment by githwxi** [comment]
I see. Merged. Thanks!

**Comment by steinwaywhw** [comment]
Now it builds docker images. I just checked the docker hub. It has the latest build under `steinwaywhw/ats:github`

**Pull request merged**
